---
generalmills:
  production:
    app1 : 
      vcocres: 0.1
      replicas: 1
    app3 : 03
  dev:
    app1: 0.2
    app2: 00.4
  qa:
    app1: 0.2
    app2: 00.4
tradepromotions:
  production:
    app1 : 0.0
    app3 : 0.1
  dev:
    app1: 0.1
    app2: 0.2
  qa:
    app1: 0.2
    app2: 00.4
